// Code generated by callgen; DO NOT EDIT.

package ccall

/*
#include <stdint.h>

static void go_call_void_uptr3_func(void (*fnc)(uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3) { fnc(a1, a2, a3); }
static void go_call_void_ptr_func(void (*fnc)(void*), void* a1) { fnc(a1); }
static void go_call_void_ptr2_func(void (*fnc)(void*, void*), void* a1, void* a2) { fnc(a1, a2); }
static void go_call_void_ptr3_func(void (*fnc)(void*, void*, void*), void* a1, void* a2, void* a3) { fnc(a1, a2, a3); }
static int go_call_int_uptr3_func(int (*fnc)(uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3) { return fnc(a1, a2, a3); }
static int go_call_int_uptr4_func(int (*fnc)(uintptr_t, uintptr_t, uintptr_t, uintptr_t), uintptr_t a1, uintptr_t a2, uintptr_t a3, uintptr_t a4) { return fnc(a1, a2, a3, a4); }
static int go_call_int_ptr2_func(int (*fnc)(void*, void*), void* a1, void* a2) { return fnc(a1, a2); }
static int go_call_int_ptr3_func(int (*fnc)(void*, void*, void*), void* a1, void* a2, void* a3) { return fnc(a1, a2, a3); }

*/
import "C"
import "unsafe"

func CallVoidUPtr3(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr) {
	C.go_call_void_uptr3_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3))
}

func CallVoidPtr(fnc unsafe.Pointer, a1 unsafe.Pointer) {
	C.go_call_void_ptr_func((*[0]byte)(fnc), a1)
}

func CallVoidPtr2(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer) {
	C.go_call_void_ptr2_func((*[0]byte)(fnc), a1, a2)
}

func CallVoidPtr3(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer) {
	C.go_call_void_ptr3_func((*[0]byte)(fnc), a1, a2, a3)
}

func CallIntUPtr3(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr) int {
	return int(C.go_call_int_uptr3_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3)))
}

func CallIntUPtr4(fnc unsafe.Pointer, a1 uintptr, a2 uintptr, a3 uintptr, a4 uintptr) int {
	return int(C.go_call_int_uptr4_func((*[0]byte)(fnc), C.uintptr_t(a1), C.uintptr_t(a2), C.uintptr_t(a3), C.uintptr_t(a4)))
}

func CallIntPtr2(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer) int {
	return int(C.go_call_int_ptr2_func((*[0]byte)(fnc), a1, a2))
}

func CallIntPtr3(fnc unsafe.Pointer, a1 unsafe.Pointer, a2 unsafe.Pointer, a3 unsafe.Pointer) int {
	return int(C.go_call_int_ptr3_func((*[0]byte)(fnc), a1, a2, a3))
}
